#!/bin/bash
#SBATCH -p shared 
#SBATCH -c 1                
#SBATCH --mem=2G            
#SBATCH --gres=tmp:3G       
#SBATCH -t 01:00:00     
#SBATCH --job-name=S04download_genome_and_gtf # This name will let you follow your job
#SBATCH --output=../log/S04download_genome_and_gtf%A_%a.out
#SBATCH --error=../log/S04download_genome_and_gtf%A_%a.err
#SBATCH --array=1
cd ~/diss
work_dir="genome"
if [ ! -d $work_dir ]
then
    mkdir $work_dir
fi
cd ${work_dir}
wget -nc https://ftp.ensembl.org/pub/release-116/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
wget -nc https://ftp.ensembl.org/pub/release-116/gtf/homo_sapiens/Homo_sapiens.GRCh38.116.gtf.gz
