#!/bin/bash
#SBATCH -p shared 
#SBATCH -c 1                
#SBATCH --mem=2G           
#SBATCH --gres=tmp:3G      
#SBATCH -t 01:00:00     
#SBATCH --job-name=S11multiqc1 
#SBATCH --output=../log/S11multiqc1%A_%a.out
#SBATCH --error=../log/S11multiqc1%A_%a.err
#SBATCH --array=1
#Runtime about 1 minute
cd ~/diss
out_dir=multiqc_report
if [ ! -d $out_dir ]
then
  mkdir $out_dir
fi
module load bioinformatics
module load  multiqc/1.35
export PYTHONIOENCODING=utf-8 #Set the Python encoding to UTF-8
#multiqc  --help # to display the help page
multiqc --force \
  --outdir ${out_dir} \
  --filename multiqc1 \
  ~/diss/fastqc
