#!/bin/bash
#SBATCH -p shared 
#SBATCH -c 1                
#SBATCH --mem=16G            
#SBATCH --gres=tmp:24G       
#SBATCH -t 01:00:00     
#SBATCH --job-name=S17multiqc3 
#SBATCH --output=../log/S17multiqc3%A_%a.out
#SBATCH --error=../log/S17multiqc3%A_%a.err
#SBATCH --array=1
#Runtime is about 2 minute

#The mapping statistics for all samples can be combined using multiqc as follows:
cd ~/diss/multiqc_report
module load bioinformatics
module load multiqc/1.35
export PYTHONIOENCODING=utf-8 #Set the Python encoding to UTF-8
multiqc --force -n multiqc3 ~/diss/star_output

multiqc --force -n multiqc_all ~/diss
